#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")

if env["disable_2d"]:
    if env.editor_build:
        env.add_source_files(env.scene_sources, "node_2d.cpp")
        env.add_source_files(env.scene_sources, "sprite_2d.cpp")
else:
    env.add_source_files(env.scene_sources, "*.cpp")
    # Chain load SCsubs
    if not env["disable_physics_2d"]:
        SConscript("physics/SCsub")
