#!/usr/bin/env python

Import("env")

if env["disable_2d"]:
    env.add_source_files(env.scene_sources, "visibility_notifier_2d.cpp")
    if env["tools"]:
        env.add_source_files(env.scene_sources, "node_2d.cpp")
        env.add_source_files(env.scene_sources, "sprite_2d.cpp")
else:
    env.add_source_files(env.scene_sources, "*.cpp")
